name: Deploy website on push

on:
  push:
    branches:
      - dev

jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Get latest code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install

      - name: Build with swc
        run: npm run build

      - name: Sync files to FTP
        uses: SamKirkland/FTP-Deploy-Action@4.1.0
        with:
          server: ftp.showmeelove.com
          username: buildforge@buildforge.xyz
          password: buildforge2024.
          local-dir: dist/
          server-dir: /
